import pandas as pd
import numpy as np
import re

from nltk import RegexpTokenizer

def clean_punctuation(sentence):
    sentence = re.sub(r"(?<=\A)([.?!-,:;\"\-])+|([.?!-,:;\"\-])+(?=\Z)", '', sentence)
    sentence = re.sub(r"(?<=\s)([.?!-,:;\"\-])+|([.?!-,:;\"\-])+(?=\s)", '', sentence)
    return re.sub(r"([.?!-,:;\"\-]){2,}", '', sentence)

def corpusize(df, column):
    tokenizer = RegexpTokenizer('\S+')
    corpus = {}

    for line in df[column].values:
        #strip excess puncutation
        line = clean_punctuation(line)
        for word in tokenizer.tokenize(line):
            word = word.lower()
            if word not in corpus:
                corpus[word] = 1
            else:
                corpus[word] += 1

    return {k: v for k, v in sorted(corpus.items(), key=lambda item: item[1], reverse = True)}

def shakespeare_contractions_dict():
    return {
            "'t": "it",
            "t'": "to",
            "ta'en": "taken",
            "e'en": "even",
            "fall'n": "fallen",
            "threat'ning": "threatening",
            "wand'ring": "wandering",
            "wat'ry": "watery",
            "ev'ry": "every",
            "ev'n": "even",
            "med'cine": "medicine",
            "ling'ring": "lingering",
            "boist'rous": "boisterous",
            "murd'rous": "murderous",
            "desp'rate": "desperate",
            "reck'ning": "reckoning",
            "wond'ring": "wondering",
            "sland'rous": "slanderous",
            "count'nance": "countenance",
            "mock'ry": "mockery",
            "murd'ring": "murdering",
            "batt'ry": "battery",
            "tend'ring": "tendering",
            "list'ning": "listening",
            "tott'ring": "tottering",
            "flow'ring": "flowering",
            "giv'n": "given",
            "fee'd": "payed",
            "numb'ring": "numbering",
            "suff'rance": "sufferance",
            "adult'ress": "adulteress",
            "swoll'n": "swollen",
            "rememb'ring": "remembering",
            "rememb'rest": "remembers",
            "flow'ry": "flowery",
            "diff'ring": "differing",
            "suff'ring": "suffering",
            "slipp'ry": "slippery",
            "med'cinable": "medicinable",
            "slaught'ring": "slaughtering",
            "distemp'rature": "distemperature",
            "off'ring": "offering",
            "glist'ring": "glistering",
            "card'nal": "cardinal",
            "off'rings": "offerings",
            "lott'ry": "lottery",
            "whisp'ring": "whispering",
            "vot'ress": "votress",
            "swagg'ring": "swaggering",
            "prepost'rously": "preposterously",
            "inter'gatories": "interogatories",
            "oferta'en": "overtaken",
            "prosp'rous": "prosperous",
            "conqu'ring": "conquering",
            "utt'rance": "utterance",
            "clamb'ring": "clambering",
            "encount'ring": "encountering",
            "overta'en": "overtaken",
            "temp'rately": "temperately",
            "h'as": "he has",
            "tow'ring": "towering",
            "cap'ring": "capering",
            "glitt'ring": "glittering",
            "blust'ring": "blustering",
            "show'ring": "showering",
            "temp'ring": "tempering",
            "crook'd": "crooked",
            "flatt'ring": "flattering",
            "rend'ring": "rendering",
            "clust'ring": "clustering",
            "heav'ns": "heavens",
            "call'dst": "called",
            "chatt'ring": "chattering",
            "ent'ring": "entering",
            "dark'ning": "darkening",
            "heav'nly": "heavenly",
            "temp'rance": "temperance",
            "heav'n": "heaven",
            "dang'rous": "dangerous",
            "eas'ly": "easily",
            "simp'ring": "simpering",
            "prepost'rous": "preposterous",
            "quick'ning": "quickening",
            "advent'rous": "adventerous",
            "mista'en": "mistaken",
            "blubb'ring": "blubbering",
            "bitt'rest": "bitterest",
            "int'rest": "interest",
            "beck'ning": "beckoning",
            "ord'ring": "ordering",
            "show'rs": "showers",
            "hind'ring": "hindering",
            "phys'nomy": "physiognomy",
            "butt'ring": "buttering",
            "threat'ningly": "threateningly",
            "discov'ryseek": "discoveryseek",
            "liv'ry": "livery",
            "recov'ry": "recovery",
            "squand'ring": "squandering",
            "se'nnight": "week",
            "palt'ring": "paltering",
            "hard'ning": "hardening",
            "dark'ned": "darkened",
            "pest'ring": "pestering",
            "marv'llous": "marvellous",
            "ord'nance": "ordinance",
            "eas'liest": "most easily",
            "length'ning": "lengthening",
            "sulf'rous": "sulfurous",
            "gard'ners": "gardeners",
            "plast'ring": "plastering",
            "rend'ring": "rendering",
            "minist'ring": "ministering",
            "flow'rets": "flowerets",
            "j'oublie": "j'oublie",
            "slobb'ry": "slobbery",
            "mock'ries": "mockeries",
            "furth'rance": "furtherance",
            "powd'ring": "powdering",
            "bach'lorship": "bachelorship",
            "suck'dst": "sucked",
            "short'ning": "shortening",
            "lov'dst": "loved",
            "cow'red": "cowered",
            "trait'rous": "traiterous",
            "strength'ning": "strengthening",
            "sov'reigns": "sovereigns",
            "pow'rful": "powerful",
            "rav'nous": "ravenous",
            "boist'rous": "boisterous",
            "threat'ner": "threatener",
            "ang'ring": "angering",
            "unfee'd": "unpayed",
            "wat'rish": "watery",
            "pilf'rings": "pilferings",
            "flick'ring": "flickering",
            "sepulch'ring": "entombing",
            "sulph'rous": "sulphurous",
            "op'ning": "opening",
            "fost'ring": "fostering",
            "slumb'ry": "slumbery",
            "whisp'rings": "whisperings",
            "sev'nnights": "weeks",
            "vap'rous": "vaporous",
            "temp'rate": "temperate",
            "oft'ner": "more often",
            "med'cines": "medicines",
            "reck'nings": "reckonings",
            "distemp'ring": "distempering",
            "mamm'ring": "wavering",
            "wond'ringly": "wonderingly",
            "deaf'ning": "deafening",
            "thund'ring": "thundering",
            "gard'ner": "gardener",
            "ha'rfordwest": "Haverfordwest",
            "monast'ry": "monastery",
            "marv'lous": "marvelous",
            "check'ring": "checkering",
            "fest'ring": "festering",
            "pop'rin": "poperin",
            "light'ning": "lightening",
            "desp'rately": "desperately",
            "moi'ty": "part",
            "christ'ning": "christening",
            "inter'gatory": "interogatory",
            "cap'ring": "capering",
            "shudd'ring": "shuddering",
            "fopp'ry": "foppishness",
            "jack'nape": "jackanape",
            "dean'ry": "deanery",
            "wat'ry": "watery",
            "sev'ral": "several",
            "em'rald": "emerald",
            "heark'ning": "listening",
            "brav'ry": "bravery",
            "knav'ry": "knavery",
            "off'rest": "offers",
            "fing'ring": "fingering",
            "vow'dst": "vowed",
            "suff'rers": "sufferers",
            "diff'rence": "difference",
            "intemp'rate": "intemperate",
            "blist'ring": "blistering",
            "mast'ry": "mastery",
            "penn'orth": "pennyworth",
            "deaf'ning": "deafening",
            "sev'nnight": "week",
            "hard'ning": "hardening",
            "underta'en": "undertaken",
            "hast'ningin": "hasteningin",
            "alt'ring": "altering",
            "far'r": "farer",
            "glutt'nous": "gluttinous",
            "sold'rest": "solders",
            "gen'ral": "general",
            "thund'rest": "thunders",
            "sust'nance": "sustenance",
            "flatt'ry": "flattery",
            "sequest'ring": "sequestering",
            "regist'red": "registered",
            "t'other": "the other",
            "thiev'ry": "thievery",
            "mapp'ry": "mappery",
            "reverb'rate": "reverberate",
            "int'rim": "interim",
            "chev'ril": "cheveril",
            "butt'ry": "buttery"
    }
