def ofer_dict():
    return {
             'ofercharged': 'overcharged',
             'oferlook':  'overlook',
             'oferrules':  'overrules',
             'oferbears':  'overbears',
             'oferflow':  'overflow',
             'oferflows':  'overflows',
             'ofertaken':  'overtaken',
             'ofercount':  'overcount',
             'ofertake':  'overtake',
             'oferthrown':  'overthrown',
             'oferflowing':  'overflowing',
             'oferpicturing':  'overpicturing',
             'oferpowered':  'overpowered',
             'ofergrown':  'overgrown',
             'oferheard':  'overheard',
             'oferrun':  'overrun',
             'oferbear':  'overbear',
             'ofercome':  'overcome',
             'oferpressed':  'overpressed',
             'oferwhelmed':  'overwhelmed',
             'oferleap':  'overleap',
             'oferpeer':  'overpeer',
             'oferwhelm':  'overwhelm',
             'oferborne':  'overborne',
             'oferjoyed':  'overjoyed',
             'oferrate':  'overrate',
             'ofervalues':  'overvalues',
             'oferlabored':  'overlabored',
             'oferthrow':  'overthrow',
             'oferpays':  'overpays',
             'ofersways':  'oversways',
             'oferteemed':  'overteemed',
             'ofergrowth':  'overgrowth',
             'oferleavens':  'overleavens',
             'ofermaster':  'overmaster',
             'oferhanging':  'overhanging',
             'ofersized':  'oversized',
             'oferdoing':  'overdoing',
             'oferstep':  'overstep',
             'oferdone':  'overdone',
             'oferweigh':  'overweigh',
             'oferreaches':  'overreaches',
             'ofercrows':  'overcrows',
             'ofer':  'over',
             'oferrule':  'overrule',
             'ofertop':  'overtop',
             'ofertook':  'overtook',
             'oferhear':  'overhear',
             'oferhasty':  'overhasty',
             'oferraught':  'overraught',
             'oferruled':  'overruled',
             'oferturn':  'overturn',
             'oferwalk':  'overwalk',
             'oferposting':  'overposting',
             'ofershine':  'overshine',
             'oferread':  'overread',
             'oferset':  'overset',
             'oferhang':  'overhang',
             'oferblows':  'overblows',
             'oferglanced':  'overglanced',
             'oferswell':  'overswell',
             'ofercame':  'overcame',
             'ofercharging':  'overcharging',
             'ofergrow':  'overgrow',
             'oferweening':  'overweening',
             'oferweens':  'overweens',
             'ofershades':  'overshades',
             'ofermatched':  'overmatched',
             'ofergreat':  'overgreat',
             'ofermount':  'overmount',
             'ofertopping':  'overtopping',
             'ofershot':  'overshot',
             'oferwatched':  'overwatched',
             'ofersway':  'oversway',
             'ofercast':  'overcast',
             'ofermasterest':  'overmasterest',
             'oferbearing':  'overbearing',
             'oferlooked':  'overlooked',
             'oferskip':  'overskip',
             'oferlooking':  'overlooking',
             'oferpaid':  'overpaid',
             'ofereye':  'overeye',
             'oferparted':  'overparted',
             'ofergone':  'overgone',
             'oferleaps':  'overleaps',
             'oferfraught':  'overfraught',
             'oferweighs':  'overweighs',
             'ofernight':  'overnight',
             'oferfed':  'overfed',
             'ofershowered':  'overshowered',
             'oferflowed':  'overflowed',
             'oferboard':  'overboard',
             'ofershade':  'overshade',
             'oferpast':  'overpast',
             'oferworn':  'overworn',
             'ofercloyed':  'overcloyed',
             'ofercovered':  'overcovered',
             'oferperch':  'overperch',
             'oferembellished': 'overembellished',
             'ofertrip':  'overtrip',
             'oferstare':  'overstare',
             'oferreaching':  'overreaching',
             'oferstunk':  'overstunk',
             'oferprized':  'overprized',
             'oferslips':  'overslips',
             'oferween':  'overween',
             'oferdyed':  'overdyed',
             'ofernightos':  'overnightos',
             'oferruns':  'overruns',
             'oferreach':  'overreach',
             'oferspreads':  'overspreads',
             'oferwrested':  'overwrested',
             'oferdusted':  'overdusted',
             'oferflourished':  'overflourished'
             }

def oring_dict():
    return {
             'tottoring':  'tottering',
             'buttoring':  'buttering',
             'encountoring': 'encountering',
             'paltoring':  'paltering',
             'pestoring':  'pestering',
             'slaughtoring': 'slaughtering',
             'plastoring':  'plastering',
             'ministoring':  'ministering',
             'glittoring':  'glittering',
             'blustoring':  'blustering',
             'flattoring':  'flattering',
             'glistoring':  'glistering',
             'clustoring':  'clustering',
             'chattoring':  'chattering',
             'entoring':  'entering',
             'fostoring':  'fostering',
             'festoring':  'festering',
             'blistoring':  'blistering',
             'altoring':  'altering',
             'sequestoring': 'sequestering'
            }

def anachronisms_dict():
    return {
            'o': 'oh',
            'thou': 'you',
            'thy': 'your',
            'tis': 'it is',
            'ere': 'before',
            'shalt': 'will',
            'thyself': 'yourself',
            'twere': 'it were',
            'handicraftman': 'craftsman',
            'cavalery': 'cavalry',
            'alack': 'alas',
            'eyne': 'eyes',
            'wot': 'what',
            'persever': 'persevere',
            'momentany': 'momentary',
            'watory': 'watery',
            'nointed': 'anointed',
            'flewed': 'flew',
            'leathern': 'leathery',
            'yond': 'yonder',
            'whatsomever': 'whatsoever',
            'twas': 'it was',
            'twould': 'it would',
            'threatoningly': 'threateningly',
            'tween': 'between',
            'twixt': 'between',
            'holp': 'hope',
            'sdeath': 'god death',
            'sblood': 'god blood',
            'unproperly': 'improperly',
            'underpeep': 'underlook',
            'madded': 'provoking madness',
            'noyance': 'annoyance',
            'methinks': 'i think',
            'thee': 'you',
            'thine': 'your',
            'gleek': 'insult',
            'mustardseed': 'mustard seed',
            'giantlike': 'giant like',
            'neaf': 'hand',
            'methought': 'i thought',
            'stoldn': 'stolen',
            'misprize': 'despize',
            'bankrout': 'bankrupt',
            'prevailment': 'prevail',
            'villagery': 'village',
            'huswife': 'housewife',
            'brisky': 'lively',
            'scaped': 'escaped',
            'unheedy': 'incautious',
            'fie': 'shit',
            'sphery': 'spherical',
            'superpraise': 'overpraise',
            'lo': 'look',
            'beteem': 'grant',
            'whither': 'where',
            'erewhile': 'a short time',
            'bedabbled': 'sprinkled',
            'misgraffed': 'poorly matched',
            'interchained': 'linked',
            'oes': 'sad',
            'ethiop': 'african',
            'votress': 'votaress',
            'overcanopied': 'canopied',
            'pard': 'leopard',
            'misprision': 'mistake',
            'flouriets': 'flowrets',
            'hight': 'high rank',
            'loffe': 'laugh',
            'neeze': 'sneeze',
            'mechanicals': 'mechanical objects',
            'aye': 'yes',
            'behowls': 'howls',
            'fordone': 'exhausted',
            'lakin': 'lady',
            'stepdame': 'step mother',
            'distemperature': 'ailment',
            'hiems': 'winter',
            'childing': 'fertile',
            'apricocks': 'apricot',
            'entwist': 'encircle',
            'enring': 'encircle',
            'approof': 'affirmation',
            'forehorse': 'foremost horse',
            'prithee': 'please',
            'misdoubt': 'disbelieve',
            'enwombed': 'born',
            'whereof': 'through which',
            'appeach': 'denounce',
            'misprizing': 'despizing',
            'betake': 'resort',
            'howsomever': 'howsoever',
            'quatch': 'squat',
            'taffety': 'overdressed',
            'quean': 'hussy',
            'carbonadoed': 'cut',
            'underminers': 'sappers',
            'adoptious': 'adopted',
            'heedfull': 'heedfull',
            'torcher': 'torch carrier',
            'ravin': 'ravenous', 
            'officed': 'functional',
            'consolate': 'console',
            'etc': 'etcetera',
            'prejudicates': 'prejudge',
            'haggish': 'hideous',
            'questant': 'seeker',
            'inaidible': 'cannot be helped',
            'empirics': 'science',
            'practicer': 'practicioner',
            'dropsied': 'pretentious',
            'foregoers': 'forebears',
            'compt': 'held in trust',
            'necessitied': 'necessary',
            'forepast': 'past',
            'araise': 'raise from the dead',
            'quicklier': 'quickly',
            'offendress': 'offender',
            'unthankfulness': 'ungratefulness',
            'swordmen': 'swordsmen',
            'facinorous': 'villainous',
            'interogatories': 'questions',
            'shrieve': 'sheriff',
            'spake': 'spoke',
            'hilding': 'worthless',
            'armipotent': 'mighty',
            'sithence': 'since',
            'brokes': 'bargains',
            'dumbed': 'silenced',
            'dungy': 'filty',
            'weet': 'know',
            'earing': 'ploughing',
            'inhooped': 'cage fight',
            'overcount': 'outnumbered',
            'semblable': 'comparable',
            'lated': 'belated',
            'lieutenantry': 'use subordinates',
            'unnoble': 'ignoble',
            'stroyed': 'destroyed',
            'gneius': 'genius',
            'boggler': 'frightened staring',
            'loathness': 'reluctance',
            'plighter': 'one who promises',
            'yare': 'deft',
            'mislike': 'dislike',
            'enfranched': 'enfranchised',
             'daff': 'take off', 
             'betime': 'early',
             'discandy': 'dissolve',
             'crownet': 'prince',
             'avaunt': 'farewell',
             'plumpy': 'plump',
             'derogately': 'disparagingly',
             'stablishment': 'establishment',
             'unbewailed': 'unmourned',
             'vant': 'front line',
             'unreconciliable': 'irreconciliable',
             'equalness': 'equality',
             'homager': 'vassal',
             'meetly': 'moderate',
             'unseminared': 'emasculated',
             'wott': 'what',
             'burgonet': 'helmet',
             'unpeople': 'depopulate',
             'unhair': 'remove hair',
             'dispraised': 'reproached',
             'discandying': 'dissolving',
             'pelleted': 'full of hail',
             'varletry': 'ruffians',
             'crownets': 'princes',
             'immoment': 'trifling',
             'misthought': 'misjudged',
             'lictors': 'enforcing officer',
             'extemporally': 'impromptu',
             'chare': 'chore',
             'intrinsicate': 'complicated',
             'unpolicied': 'outwitted in intrigue',
             'falliable': 'infallible',
             'splitted': 'broken apart',
             'augurer': 'prophet',
             'overpicturing': 'surpassing',
             'yarely': 'deftly',
             'riggish': 'licentious',
             'unexecuted': 'unused',
             'mered': 'entire',
             'unstate': 'dispossess',
             'sworder': 'gladiator',
             'estridge': 'goshawk',
             'outstrike': ' surpass in striking',
             'dispunge': 'discharge',
             'rivality': ' equal partnership',
             'soothsay': 'foresee',
             'uncuckolded': 'not cuckolded',
             'unqualitied': 'unmanned',
             'curstness': ' bad temper',
             'trull': 'whore',
             'drave': 'drove',
             'cloyless': ' never satiating',
             'surfeiter': 'profligate',
             'unhacked': 'unused',
             'undinted': 'without dents',
             'tokened': 'spotted',
             'ribaudred': 'obscene',
             'loofed': 'brought into the wind',
             'droven': 'driven',
             'raught': 'reached',
             'beloving': 'loving',
             'coz': 'cousin',
             'trow': 'wonder',
             'pickpurse': 'cutpurse',
             'intendment': 'intention',
             'boldened': 'emboldened',
             'invectively': 'vehemently',
             'stanzo': 'verse',
             'stanzos': 'verses',
             'chanticleer': 'rooster',
             'misprized': 'despized',
             'rustically': 'splendidly',
             'allottery': 'allocation',
             'quintain': ' heavy post used as a mark for tilting practice',
             'cheerly': 'heartily',
             'impressure': 'imprint',
             'ungentleness': 'boorishness',
             'ungartered': 'lovesick',
             'moonish': 'capricious',
             'entame': 'tame',
             'pathetical': 'pathetic',
             'thrasonical': 'boastful',
             'extermined': 'exterminated',
             'carlot': 'peasant',
             'batler': 'clothes washer',
             'perpend': 'consider',
             'cuckoldly': 'with the character of a cuckold',
             'scrippage': 'baggage',
             'ild': 'reward',
             'hitherward': 'towards this place',
             'afric': 'african',
             'potch': 'thrust',
             'fane': 'temple',
             'whereagainst': ' against which place',
             'fisting': 'punching',
             'empoisoned': 'poisoned',
             'giber': 'joker',
             'bencher': 'magistrate',
             'malkin': 'slut',
             'lockram': 'linen',
             'reechy': 'discoloured',
             'seld': 'rarely',
             'gauded': 'gaudy',
             'dispropertied': 'dispossessed',
             'provand': 'provisions',
             'plebeii': 'plebians',
             'youngly': 'early in life',
             'haver': 'possessor',
             'overpressed': 'overwhelmed',
             'shunless': 'inescapable',
             'fatigate': 'fatigued',
             'larum': 'alarm',
             'agued': 'shivering',
             'ope': 'open',
             'doit': 'trifle',
             'bedward': ' showing the way towards bed',
             'budger': 'shrinker',
             'ovator': ' one who receives an ovation',
             'hyperbolical': 'outrageous',
             'howbeit': 'although',
             'undercrest': ' live up to',
             'counterfeitly': 'feignedly',
             'toge': 'toga',
             'overpeer': 'overlook',
             'antium': '',
             'meiny': 'household',
             'tetter': 'cover the skin with scabs',
             'vail': 'setting',
             'unbarbed': 'unprotected',
             'cautelous': 'cautious',
             'unseparable': 'inseparable',
             'interjoin': 'unite',
             'unvulnerable': 'invulnerable',
             'unbuild': 'demolish',
             'directitude': 'discredit',
             'getter': 'begetter',
             'dotant': 'dullard',
             'shent': 'shame',
             'guider': 'guide',
             'unactive': 'inactive',
             'whereby': 'by which',
             'infantlike': 'infantile',
             'bisson': 'dazzling',
             'conspectuities': 'insights',
             'rejourn': 'postpone',
             'empiricutic': 'fraudulent',
             'unscanned': 'thoughtless',
             'unapt': 'unfit',
             'factionary': 'partisan',
             'spectatorship': 'display before spectators',
             'differency': 'difference',
             'ingrateful': 'ungrateful',
             'strucken': 'wounded',
             'cannibally': ' in the manner of a cannibal',
             'convented': 'convened',
             'portance': 'behaviour',
             'ungravely': 'derisively',
             'unknit': 'unravel',
             'sowl': 'pull',
             'freelier': 'unreservedly',
             'unsevered': 'inseparable',
             'valiantness': 'valiance',
             'foxship': 'slyness',
             'loaden': 'laden',
             'foresay': 'predict',
             'sharded': 'with scales',
             'resty': 'lazy',
             'divineness': 'divinity',
             'enchafed': 'furious',
             'crare': 'small trading boat',
             'chaliced': ' with cupshaped blossom',
             'pantler': 'pantry butler',
             'insultment': 'derision',
             'rejoicingly': 'with delight',
             'imperceiverant': 'undiscerning',
             'lud': 'London',
             'tendance': 'people in attendance',
             'forespent': 'previously shown',
             'unkinglike': 'not regal',
             'freeness': 'generosity',
             'hardiment': 'daring deed',
             'whereunto': ' to which',
             'supplyant': ' ready to supply',
             'attemptable': ' capable of being seduced',
             'throughly': 'thoroughly',
             'reck': 'regard',
             'unlaid': 'undisclosed',
             'obsequies': 'obsequious',
             'incivil': 'discourteous',
             'princelike': 'princely',
             'outlusters': 'outshines',
             'unparagoned': 'unsurpassable',
             'unprizable': 'worthless',
             'thereupon': ' upon that',
             'sluttery': 'sluttishness',
             'gamesome': 'playful',
             'venge': 'avenge',
             'illustrous': 'dull',
             'empery': 'sovereignty',
             'runagate': 'rebel',
             'chaffless': 'unsullied',
             'cherubins': 'cherubs',
             'revengingly': 'in retaliation',
             'carl': 'peasant',
             'pight': 'fixed',
             'dispraising': 'critically',
             'trulls': 'whores',
             'unspeaking': 'incapable of speech',
             'simular': 'fake',
             'whereupon': 'upon which',
             'puttock': 'greedy scavenger',
             'overbuys': 'pay too much for',
             'neatherd': 'cowherd',
             'medicinable': 'medicinal',
             'untender': 'unkind',
             'winterly': 'cheerless',
             'afore': 'before',
             'disedged': 'have appetite satisfied',
             'outpeer': 'outrival',
             'pittikins': ' dear pity',
             'irregulous': 'uncontrollable',
             'maintop': 'platform near the top',
             'untendered': 'unpaid',
             'arrearages': 'overdue payments',
             'fedary': 'accomplice',
             'quarrelous': 'argumentative',
             'cloakbag': ' bag for carrying clothes',
             'supplyment': 'ongoing provision',
             'betid': 'befall',
             'statist': 'politician',
             'pudency': 'shyness',
             'slaughterman': 'executioner',
             'grandsire': 'grandfather',
             'fangled': 'trendy',
             'whenas': 'when',
             'justicer': 'judge',
             'spritely': 'cheerful',
             'allayments': 'mitigation',
             'depender': 'dependant',
             'remembrancer': ' official reminder',
             'handfast': 'under arrest',
             'geck': 'fool',
             'mollis': ' soft air',
             'crants': 'wreath',
             'eterne': 'eternal',
             'mobled': 'veiled',
             'overteemed': 'excessively productive',
             'porpentine': 'porcupine',
             'rankly': 'completely',
             'hebona': ' poisonous plant',
             'distilment': 'distillation',
             'unhouseled': 'without communion',
             'unaneled': 'without extreme unction',
             'matin': 'morning',
             'uneffectual': 'ineffective',
             'nill': 'will not',
             'crowner': 'coroner',
             'ditchers': 'ditch maker',
             'pocky': 'poxy',
             'upspring': 'trendy',
             'clepe': 'call',
             'overleavens': 'imbue to excess',
             'hillo': ' falconer cry to bring a hawk down',
             'truepenny': ' honest fellow',
             'friending': 'friendliness',
             'consonancy': 'accord',
             'majestical': 'grand',
             'valanced': 'fringed',
             'uncurrent': 'aberrant',
             'caviary': 'caviare',
             'gules': 'red',
             'impasted': 'crusted',
             'bodykins': 'gods dear body',
             'unpregnant': 'unready',
             'overweigh': 'exceed',
             'unkennel': 'reveal',
             'stithy': 'forge',
             'miching': 'sneaking',
             'mallecho': 'misdeed',
             'unwrung': 'not chafed',
             'ungalled': 'uninjured',
             'pajock': 'degenerate',
             'stonish': 'astonish',
             'hent': 'reach',
             'apoplexed': 'paralysed',
             'thralled': 'enslaved',
             'mutine': 'mutiny',
             'enseamed': 'slimy',
             'fust': 'grow mouldy',
             'chapless': 'jawless',
             'pah': 'disgust',
             'fordo': 'destroy',
             'splenitive': 'angry temperament',
             'eisel': 'vinegar',
             'mutines': 'mutinies',
             'bilboes': 'shackles',
             'benetted': 'ensnared',
             'statists': 'politicians',
             'debatement': 'deliberation',
             'ordinant': 'providential',
             'definement': 'description',
             'inventorially': 'in detail',
             'concernancy': 'relevance',
             'drossy': 'foolish',
             'whensoever': 'whenever',
             'gaingiving': 'apprehension',
             'parle': 'discuss',
             'sledded': ' carried by sleds',
             'compulsatory': ' involving compulsion',
             'foresaid': 'aforesaid',
             'posthaste': ' great expedition',
             'tenantless': 'without tenants',
             'precurse': 'precursor',
             'climatures': 'regions',
             'uphoarded': 'hoard',
             'yesternight': ' last night',
             'attent': 'attentive',
             'impartment': 'communication',
             'jointress': 'dowager',
             'colleagued': 'supported',
             'condolement': 'lamenting',
             'unprevailing': 'unsuccessful',
             'woundless': 'invulnerable',
             'swoopstake': 'indiscriminately ',
             'unsinewed': 'feeble',
             'thereunto': 'matter',
             'uncharge': 'acquit of blame',
             'sanctuarize': 'shelter',
             'unbated': 'unabated',
             'primy': 'in its prime',
             'suppliance': 'diversion',
             'thews': 'sinews',
             'cautel': 'trickery',
             'credent': 'trustworthy',
             'unmastered': 'uncontrolled',
             'unsmirched': 'unstained',
             'hatchment': 'heraldry tablet',
             'skyish': 'lofty',
             'reconcilement': 'reconciliation',
             'ungored': 'unharmed',
             'springe': 'snare',
             'illo': ' falconer cry to bring a hawk down',
             'impiteous': 'impetuous',
             'redeliver': 'repeat',
             'shoon': 'shoes',
             'dild': 'reward',
             'infallibly': 'accurately',
             'unfellowed': 'unrivalled',
             'delver': 'excavator',
             'commutual': 'mutual',
             'enactures': 'performance',
             'unproportioned': 'immoderate',
             'unsifted': 'inexperienced',
             'drabbing': 'whoring',
             'unreclaimed': 'untamed',
             'prenominate': 'previously mentioned',
             'fordoes': 'destroy',
             'individable': 'indivisible',
             'vailed': 'lowered',
             'incorporal': 'incorporeal',
             'crowflowers': 'robin',
             'tyrannically': 'outrageously',
             'berattle': 'fill with clamour',
             'overraught': 'overreach',
             'massy': 'massive',
             'annexment': 'attachment',
             'corrivals': 'compete with',
             'beslubber': 'spread thickly',
             'zounds': 'gods wounds',
             'gorbellied': 'fat paunched',
             'jure': ' make a juror of',
             'netherstocks': ' stocking for the lower leg',
             'shotten': 'spawned',
             'ecce': ' behold the evidence',
             'ebrew': 'hebrew',
             'afront': 'abreast',
             'elfskin': 'mere nothing',
             'pizzle': 'penis',
             'tristful': 'dismal',
             'micher': 'truant',
             'poulter': 'poulterer',
             'applejohn': 'apple ',
             'ignis': 'fire',
             'fatuus': 'foolish',
             'godamercy': 'god have mercy',
             'partlet': 'hen ',
             'dowlas': ' cheap coarse linen',
             'unprovided': 'unprepared',
             'gurnet': 'fish insult large head',
             'caliver': 'musket',
             'servingmen': 'male servant',
             'draff': 'garbage',
             'unlooked': 'unanticipated',
             'embowel': 'disembowel',
             'troyans': 'trojans',
             'vizards': 'mask',
             'vasty': 'immense',
             'pouncet': 'box',
             'unhandsome': 'faulty',
             'neglectingly': 'neglectfully',
             'downtrod': 'downtrodden',
             'corrival': 'compete with',
             'cozeners': 'fraud',
             'esperance': 'optimism',
             'whereabout': 'whereabouts',
             'grandam': 'grandmother',
             'moldwarp': 'mole',
             'moulten': ' having moulted',
             'skimble': 'incoherent',
             'skamble': 'incoherent',
             'brach': 'hound',
             'justling': 'chaotic',
             'topsy': 'upside down',
             'turvy': 'upside down',
             'daffed': 'throw off',
             'semblably': 'similarly',
             'revengement': 'punishment',
             'mistreadings': 'transgression',
             'forethink': 'anticipate',
             'bavin': 'firewood',
             'hurlyburly': 'commotion',
             'impaint': 'portray',
             'pellmell': 'confusion',
             'hest': 'command',
             'paraquito': 'parakeet',
             'immask': 'witted',
             'moorditch': 'filthy channel',
             'allhallown': 'period of fine weather in late autumn',
             'uncolted': 'deprived of a horse',
             'underskinker': 'tapster',
             'leathern': 'clothed in animal skins',
             'caddis': 'tape made of worsted yarn',
             'rivo': 'exclamation',
             'chewet': 'chatterer',
             'unrevenged': 'unavenged',
             'cital': 'account',
             'overwalk': 'walk over',
             'unsteadfast': 'unsteady',
             'outdare': 'overcome by daring',
             'sortance': 'accord',
             'overlive': 'outlast',
             'insinewed': ' joined together in strength',
             'misdoubts': 'suspect',
             'enrooted': 'entangled by the roots',
             'upreared': 'standing on end',
             'misordered': 'disordered',
             'foreruns': 'foreshadow',
 'thas': 'military drill command',
 'overposting': 'disregarding',
 'considerance': 'consideration',
 'misbecame': ' appear unbecoming to',
 'hade': 'left unploughed in a field',
 'proface': 'for your benefit',
 'foining': 'lunging',
 'saltness': 'vigour',
 'bearherd': 'bear handler',
 'halloing': 'shouting',
 'sneap': 'snub',
 'waterwork': 'watercolour',
 'undeserver': 'unworthy person',
 'assemblance': 'appearance',
 'pewterer': ' maker of pewter utensils',
 'overscutched': 'often whipped',
 'huswives': 'housewives',
 'indifferency': 'impartiality',
 'overshine': 'outshine',
 'sherris': ' white wine',
 'crudy': 'thick',
 'forgetive': 'creative',
 'servingman': ' male servant',
 'intervallums': 'break between sessions',
 'applejohns': 'apples',
 'gaultree': 'forest',
 'foin': 'thrust',
 'continuantly': 'incontinently',
 'lumbert': 'street',
 'exion': 'action',
 'honeyseed': 'homicide',
 'queller': 'killer',
 'hempseed': 'homicide',
 'wheeson': 'Whitsun',
 'goodwife': 'mistress of a household',
 'keech': ' lump of congealed fat',
 'temperality': 'temper',
 'pulsidge': 'pulses',
 'tilly': 'nonsense',
 'vally': 'nonsense',
 'tisick': ' consumptive cough',
 'debuty': 'deputy',
 'beseek': 'beseech',
 'tirrits': 'terrors fits',
 'atomy': 'tiny being',
 'unfathered': 'illegitimate',
 'intelligencer': 'informant',
 'overread': 'read through',
 'hurly': 'turmoil',
 'beachy': 'pebble covered',
 'unseconded': 'unsupported',
 'recordation': 'recollection',
 'overset': 'overturn',
 'outbreathed': 'winded',
 'accompt': 'account',
 'presurmise': 'thought in advance',
 'strengthless': 'weak',
 'rampallian': 'ruffian',
 'fustilarian': 'smelly old woman',
 'troyant': 'trojan',
 'untwind': 'untwine',
 'foutre': 'fuck',
 'besonian': 'scoundrel',
 'semper': ' always the same',
 'obsque': ' apart from this there is nothing',
 'engraffed': 'ingrained',
 'martlemas': 'fullness of being',
 'accites': 'summons',
 'descension': 'degradation',
 'biggen': 'nightcap',
 'rigol': 'ring',
 'accite': 'summon',
 'utis': 'festivity',
 'bona': 'high class',
 'robas': 'prostitute',
 'stamford': 'market',
 'roba': 'prostitute',
 'dagonet': 'fool',
 'rah': 'gun drill',
 'tah': 'noise',
 'graffing': 'grafting',
 'liggens': 'eyelids',
 'leman': 'lover',
 'samingo': 'drinking refrain',
 'mure': 'wall',
 'forspent': 'exhausted',
 'intreasured': 'safely stored',
 'perfectness': 'fullness',
 'overween': 'presume',
 'galliard': 'lively dance',
 'wheresomever': 'wherever',
 'scambling': 'struggling',
 'currance': 'current',
 'practic': 'practical',
 'severals': 'separates',
 'unhidden': 'undisputed',
 'gloze': 'expound',
 'defunction': 'decease',
 'imbar': 'exclude',
 'exampled': 'exemplified',
 'sumless': 'immeasurable',
 'contrariously': 'in opposed ways',
 'crescive': 'growing',
 'unfought': ' without being met in battle',
 'slobbery': 'slimy',
 'burnet': 'flower',
 'rosed': 'rosy',
 'threaden': 'made of linen thread',
 'rivage': 'shore',
 'sternage': 'sterns',
 'grandsires': 'aged person',
 'paly': 'pale',
 'umbered': 'shadowed',
 'overlusty': 'excessively merry',
 'gaited': 'movement',
 'inly': 'inward',
 'whiffler': ' armed processional attendant',
 'vainness': 'vanity',
 'ostent': 'display',
 'sonance': 'sound',
 'diable': 'devil',
 'redoubted': 'feared',
 'grafters': 'tree from which a graft has been taken',
 'congreeing': 'accord',
 'prived': 'bereaved',
 'misbecome': 'unbecoming',
 'womby': 'hollow',
 'insteeped': 'immersed',
 'digt': 'dug',
 'falorous': 'valorous',
 'aunchient': 'senior officer',
 'voutsafe': 'vouchsafe',
 'pridge': 'bridge',
 'prave': 'brave',
 'pless': 'bless',
 'bubukles': 'inflamed swelling',
 'plue': 'blue',
 'prerogatifes': 'prerogatives',
 'tiddle': 'chatter',
 'taddle': 'chatter',
 'pibble': 'pibble',
 'poys': 'boys',
 'offert': 'offered',
 'sall': 'shall',
 'prains': 'brains',
 'plack': 'black',
 'pattle': 'battle',
 'tavy': 'Davy',
 'plood': 'blood',
 'pody': 'body',
 'jeshu': 'Jesu',
 'aggriefed': 'aggrieved',
 'twelvepence': 'money',
 'prawls': 'brawls',
 'prabbles': 'brabble',
 'pashful': 'bashful',
 'silling': 'shilling',
 'pragging': 'bragging',
 'prings': 'brings',
 'pread': 'bread',
 'peseech': 'entreat',
 'ploody': 'bloody',
 'gleeking': 'jesting',
 'christom': 'innocent',
 'gudday': 'good day',
 'gud': 'good',
 'captens': 'captains',
 'leve': 'leave',
 'theise': 'these',
 'slomber': 'slumber',
 'lig': 'lie',
 'grund': 'ground',
 'suerly': 'surely',
 'breff': 'brief',
 'tway': 'two',
 'impawn': 'commit',
 'tombless': 'lacking a memorial',
 'ungotten': 'not yet conceived',
 'appurtenants': 'accessory',
 'jutty': 'projection',
 'enlinked': 'connected',
 'overblows': 'abates',
 'slaughtermen': 'executioners',
 'sinfully': 'without having repented of sins',
 'irreconciled': 'unabsolved',
 'intertissued': 'interwoven',
 'slovenry': 'slovenliness',
 'skirr': 'scurry',
 'wherefor': 'why',
 'advantageable': 'advantageous',
 'forerank': 'first section',
 'brokenly': ' fallen out',
 'uncoined': 'genuine',
 'untempering': 'unsoftening',
 'captived': 'captivated',
 'cursitory': 'cursory',
 'overglanced': 'glanced over',
 'perspectively': 'as if through an optical instrument',
 'chrish': 'Christ',
 'tish': 'it is',
 'ish': 'is',
 'trompet': 'trumpet',
 'basterd': 'bastard',
 'reanswer': 'answer again',
 'yerk': 'strike',
 'pish': 'contempt',
 'shog': ' go away',
 'solus': 'alone',
 'barbason': 'devil',
 'perdu': 'sentry placed in a hazardous position',
 'spital': 'hospital',
 'pauca': 'few words',
 'overswell': 'overflow',
 'fracted': 'broken',
 'caveto': 'beware',
 'huswifery': 'housewife tasks',
 'bawcock': 'fine fellow',
 'figo': 'fuck',
 'paction': 'compact',
 'pavilioned': 'in ceremonial tents',
 'rawly': 'immaturely',
 'expulsed': 'expel',
 'pucelle': 'virgin',
 'whoso': 'whoever',
 'unfallible': 'infallible',
 'invocate': 'entreat',
 'intermissive': 'intermittent',
 'inhearsed': ' as if in a coffin',
 'otherwhiles': 'on occasion',
 'sweeting': 'darling',
 'extirped': 'eradicated',
 'writhled': 'shrivelled',
 'disanimates': 'discourage',
 'stablish': 'establish',
 'reguerdon': 'recompense',
 'reguerdoned': 'recompense',
 'immanity': 'atrocious cruelty',
 'inshipped': 'embarked',
 'shipwrack': 'shipwreck',
 'neglection': 'negligence',
 'pursuivants': ' royal messenger',
 'pithless': 'feeble',
 'significants': 'indications',
 'overpassed': 'spent',
 'endamage': 'damage',
 'paysans': 'peasants',
 'giglot': 'harlot',
 'periapts': 'potions',
 'gimmers': 'mechanical joints',
 'collop': 'offspring',
 'unheedful': 'careless',
 'misconster': 'misconstrue',
 'gleeks': 'jest',
 'exequies': ' funeral rites',
 'unavoided': 'unavoidable',
 'enrank': 'draw up in battle lines',
 'agazed': 'astounded',
 'inkhorn': 'pedantic',
 'crestless': ' lacking a heraldic crest',
 'enow': 'enough',
 'proditor': 'traitor',
 'heartblood': '',
 'extemporal': 'unplanned',
 'unreverent': 'irreverent',
 'iwis': 'certainly',
 'machiavel': 'political schemer',
 'cade': 'cask',
 'handicraftsmen': 'craftsmen',
 'bandogs': ' chained dog',
 'hoise': 'hoist',
 'footcloth': 'equipped with long trappings',
 'caudle': 'potion',
 'medice': 'physician',
 'choicely': 'carefully',
 'villiago': 'scoundrel',
 'cades': 'casks',
 'indigested': 'uncompleted',
 'enchased': 'adorned',
 'uneath': 'with difficulty',
 'abrook': 'endure',
 'attainture': 'condemnation',
 'turmoiled': 'troubled',
 'emblaze': ' proclaim publicly',
 'yclad': 'decked out',
 'engirt': 'encircle',
 'infortunate': 'unfortunate',
 'affy': 'engage',
 'invitis': 'in spite of clouds',
 'gallowglasses': 'axe wielding Irish soldier',
 'uncurable': 'incurable',
 'alderliefest': 'most beloved',
 'callet': 'scold',
 'tainture': 'tainting',
 'fraudful': 'fraudulent',
 'deathful': 'mortal',
 'sophister': 'sophist',
 'customed': 'customary',
 'behoof': 'benefit',
 'charneco': 'sweet Portuguese wine',
 'shearman': ' one who shears excess material from woollen cloth',
 'sicil': 'sicily',
 'pursuivant': ' royal messenger',
 'unmeet': 'unready',
 'clerkly': 'scholarly',
 'traiterous': 'traitorous',
 'woefull': 'sorrowful',
 'occupat': 'business',
 'banditto': 'bandit',
 'spleenful': 'passionate',
 'aidance': 'assistance',
 'unbloodied': 'unharmed',
 'deathsman': 'executioner',
 'mountaintop': 'mountain top',
 'regentship': 'regency',
 'guerdoned': 'reward',
 'bestead': 'prepared',
 'politicly': 'shrewdly',
 'morisco': 'morris dancer',
 'fleur': 'royal symbol of France',
 'shriver': 'father confessor',
 'ruinate': 'reduce to ruins',
 'unconstant': 'unpredictable',
 'malapert': 'impudent',
 'sicils': 'Naples and Sicily',
 'misproud': 'arrogant',
 'cureless': 'incurable',
 'laund': 'glade',
 'forslow': 'delay',
 'easeful': 'comfortable',
 'railer': 'reviler',
 'ean': ' bring forth lambs',
 'misthink': ' think ill of',
 'overgone': 'exhausted',
 'brinish': 'salt bitter',
 'encaged': 'caged up',
 'disannuls': 'annul',
 'vere': 'where',
 'deathsmen': 'executioners',
 'opes': 'opens',
 'extraught': 'extracted',
 'cursy': 'angry',
 'overweens': 'presumes',
 'misshaped': 'misshapen',
 'di': 'may the gods cause your action to be that which makes you best known',
 'mought': 'could',
 'unwares': 'unawares',
 'haught': 'arrogant',
 'overshades': 'overshadows',
 'coverture': 'cover',
 'embassade': 'embassy',
 'belgia': 'Belgium',
 'unbid': 'unwelcome',
 'sportful': 'recreational',
 'overpeered': 'overlooked',
 'overmatched': 'outnumbered',
 'vizard': 'mask',
 'privity': 'private knowledge',
 'aboded': 'residence',
 'outworths': 'outvalues',
 'overgreat': 'imperious',
 'unpartial': 'impartial',
 'otherwhere': 'elsewhere',
 'marshalsea': 'debtor prison ',
 'mong': 'among',
 'primero': 'gambling card game',
 'unqueened': 'removed from the position of queen',
 'outspeaks': 'far exceeds',
 'halidom': 'holy swear',
 'ween': 'think',
 'vehemency': 'vehemence',
 'footboy': 'servant on foot',
 'colbrand': 'giant',
 'broomstaff': 'broomstick',
 'pibbles': 'chatters',
 'discourser': 'narrator',
 'certes': 'certainly',
 'emballing': 'investment with sovereignity',
 'overmount': 'transcend',
 'foreskirt': ' front skirts',
 'arrogancy': 'arrogance',
 'shipwracked': 'shipwrecked',
 'springhalt': 'horse twitching disease',
 'uncontemned': 'unscorned',
 'praemunire': 'traitor accusation',
 'gladding': 'delighting',
 'sacring': 'bell rung at the moment of consecration',
 'pausingly': 'haltingly',
 'revokement': 'revocation',
 'unthink': 'intentionally forget',
 'tanta': ' so great is the integrity of our purpose towards you, most noble Queen',
 'spleeny': ' hot headed',
 'unmeritable': 'unworthy',
 'insuppressive': 'irrepressible',
 'purgers': 'cleanser',
 'charactery': 'writing',
 'undeservers': 'unworthy people',
 'smatch': 'relish',
 'augurers': 'prophets',
 'preordinance': 'previously established ordinance',
 'rabblement': 'rabble',
 'oversway': 'override',
 'ungently': 'roughly',
 'unpurged': 'unpurified',
 'angerly': 'angrily',
 'absey': 'alphabet book',
 'potents': 'rulers',
 'scroyles': 'scoundrels',
 'bethumped': 'pound',
 'peised': 'poised',
 'unattempted': 'untempted',
 'scamble': 'scramble',
 'unowed': 'unowned',
 'underbear': 'endure',
 'vaulty': 'cavernous',
 'prisonment': 'imprisonment',
 'silverly': 'silvery',
 'underprop': 'support',
 'brabbler': 'brawler',
 'dispiteous': 'merciless',
 'exteriorly': 'superficially',
 'embounded': 'enclosed',
 'controlment': 'restraint',
 'endamagement': 'damage',
 'dishabited': 'dislodged',
 'forwearied': 'exhausted',
 'sprightful': 'lively',
 'mistempered': 'deranged',
 'unvexed': 'untroubled',
 'roundure': 'roundness',
 'cloddy': 'full of clods',
 'overstained': 'covered with stains',
 'regreet': 'return of salutation',
 'unswear': 'retract',
 'abortives': 'unnatural',
 'topful': 'overfull',
 'convertite': 'convert',
 'corruptibly': ' in a corruptible way',
 'unsured': 'uncertain',
 'bestained': 'marked with stains',
 'disbranch': 'sever',
 'bemonster': 'deform',
 'justicers': 'judges',
 'fumiter': 'weed',
 'aidant': 'helpful',
 'observants': 'obsequious servants',
 'awork': 'at work',
 'reprovable': 'reprehensible',
 'pillicock': 'penis',
 'suum': ' to each his own',
 'sessa': 'go hunt',
 'aroint': ' be gone',
 'smulkin': 'devil',
 'modo': 'devil',
 'mahu': 'devil',
 'frateretto': 'devil',
 'hoppedance': 'devil',
 'minikin': 'shrill',
 'lym': 'bloodhound',
 'overskip': 'pass over without noticing',
 'obidicut': 'devil',
 'impertinency': 'nonsense',
 'zir': 'sir',
 'vurther': 'further',
 'casion': 'occasion',
 'volk': 'folk',
 'chud': 'should',
 'zwaggered': 'swaggered',
 'zo': 'so',
 'vortnight': 'fortnight',
 'che': 'I',
 'vor': 'for',
 'costard': 'head',
 'ballow': 'cudgel',
 'foins': 'thrusts',
 'indistinguished': 'limitless',
 'maugre': 'in spite of',
 'conspirant': 'conspirator',
 'treachers': 'traitors',
 'ursa': 'lecher',
 'fut': 'shit',
 'alarumed': 'galvanized',
 'unpossessing': ' unable to inherit property',
 'reposal': 'reposing',
 'fordid': 'exhausted',
 'nuncle': 'master',
 'unpayed': 'unpaid',
 'forevouched': 'previously declared',
 'unprized': 'priceless',
 'outscorn': 'outstorm',
 'unbonneted': 'recklessly',
 'smilets': 'slight smiles',
 'disquietly': 'uneasily',
 'unremovable': 'immovable',
 'guessingly': 'as conjecture',
 'stelled': 'starry',
 'opposeless': 'unchallengeable',
 'waywardness': 'capriciousness',
 'disquantity': 'reduce',
 'besort': 'entourage',
 'enguard': 'protect',
 'cowish': 'cowardly',
 'reverb': 'reverberate',
 'lipsbury': 'jaws',
 'cullionly': 'rascally',
 'barbermonger': 'frequenter of the barbershop',
 'atwain': 'into two parts',
 'intrinse': 'intricate',
 'discommend': 'criticize',
 'bemadding': 'maddening',
 'outwall': 'external appearance',
 'gallow': 'frighten',
 'unfriended': 'friendless',
 'disnatured': 'unnatural',
 'untented': 'undressed',
 'beweep': 'weep over',
 'wolvish': 'wolfish',
 'hysterica': 'hysteria',
 'passio': '',
 'hurricanoes': ' water spouts',
 'pudder': 'uproar',
 'summoners': 'court officer who ensures attendance',
 'superflux': 'superfluity',
 'unaccommodated': 'not possessed of clothes',
 'yokefellow': 'comrade',
 'crowkeeper': 'scarecrow',
 'hewgh': 'arrow sound',
 'fitchew': 'skunk',
 'cozener': 'fraud',
 'thereat': 'because of that',
 'fleshment': 'successful accomplishment',
 'questrists': 'seekers',
 'epitheton': 'description',
 'outswear': 'outdo in swearing',
 'duello': 'established duelling code',
 'festinately': 'speedily',
 'tofore': 'beforehand',
 'sain': 'said',
 'chirrah': 'sirrah',
 'mediterraneum': 'Mediterranean',
 'preambulate': 'walk forth',
 'singuled': 'distinguished',
 'armado': 'armada',
 'fadge': 'succeed',
 'couplement': 'couple',
 'infamonize': 'defame',
 'woolward': 'wearing wool next to the skin',
 'wimpled': 'blindfolded',
 'dan': 'master',
 'imperator': 'emperor',
 'whitely': 'pale',
 'birdbolt': 'arrow for shooting birds',
 'triumviry': 'triumvirate',
 'overeye': 'observe',
 'pickpurses': 'pickpockets',
 'fivescore': 'one hundred',
 'forerun': 'foreshadow',
 'pedantical': 'pedantic',
 'kersey': 'ordinary',
 'squier': 'square',
 'novum': 'game of dice',
 'alisander': 'Alexander',
 'misbecomed': 'appear unbecoming',
 'indubitate': 'certain',
 'veni': 'came',
 'vidi': 'saw',
 'vici': 'conquered',
 'annothanize': 'anatomize',
 'repasture': 'meal',
 'phantasime': ' one full of fancies',
 'monarcho': 'pretentious absurdity',
 'bookmates': 'scholarly associates',
 'embassage': 'errand',
 'dismasked': 'unmasked',
 'vailing': 'setting',
 'dishclout': 'dishcloth',
 'egma': 'enigma',
 'incony': 'fine',
 'gardon': 'reward',
 'upshoot': 'final shot',
 'sola': 'hunting cry',
 'almsbasket': 'basket containing offerings to be given out for charity',
 'honorificabilitudinitatibus': '',
 'flapdragon': 'small cake',
 'pursents': 'present',
 'whereuntil': 'to which',
 'parfect': 'perform',
 'pompion': 'Pompey',
 'targe': 'shield',
 'polax': 'poleaxe',
 'overparted': 'having too difficult a part to play',
 'troyan': 'trojan',
 'bepray': 'pray',
 'farborough': 'parish officer',
 'dey': 'dairy',
 'haud': "I don't believe it",
 'pomewater': 'large juicy apple',
 'preyful': 'preying',
 'sorel': 'intensely',
 'vir': 'a wise man that says little',
 'lege': 'allege',
 'apostrophus': ' mark of elision',
 'canzonet': 'poem',
 'elegancy': 'elegance',
 'damosella': 'damsel',
 'overglance': 'glance over',
 'satis': 'that is enough which suffices',
 'phantasimes': ' one full of fancies',
 'insociable': 'intolerable',
 'abhominable': 'abominable',
 'insanie': 'madness',
 'unguem': 'to a nicety',
 'yclept': 'called',
 'sneaping': 'nipping',
 'dominator': 'ruler',
 'betook': 'committed',
 'ethiopes': 'africans',
 'glozes': 'expounds',
 'omne': ' all is well',
 'impudency': 'impudence',
 'intituled': 'entitled',
 'laus': ' God be praised I understand good',
 'unseeming': 'not seeming',
 'shrows': 'shrewdly',
 'hests': 'commands',
 'martlet': 'martin',
 'mansionry': 'place of habitation',
 'wooingly': 'enticingly',
 'procreant': 'copulator',
 'shipwracking': ' causing shipwreck',
 'norweyan': 'Norwegian',
 'sevennights': 'weeks',
 'compunctious': 'remorseful',
 'masterdom': 'supremacy',
 'limbeck': 'alembic',
 'brainsickly': 'foolishly',
 'unrough': 'beardless',
 'ingredience': 'ingredients',
 'cherubin': 'heavenly beauty',
 'sleave': 'threads',
 'pauser': 'circumspect',
 'unlineal': 'not of the same family',
 'gospeled': 'converted',
 'shoughs': 'dogs',
 'clept': 'called',
 'rooky': 'dark',
 'bodements': 'portent',
 'boltered': 'strained',
 'firstlings': 'opening events',
 'disseat': 'remove',
 'dareful': 'audacious',
 'direness': 'horror',
 'intrenchant': 'uncuttable',
 'birthdom': 'native land',
 'affeered': 'settled',
 'foisons': 'abundance',
 'undeeded': 'without any deeds performed',
 'unfelt': 'not experienced',
 'confineless': 'boundless',
 'stanchless': 'insatiable',
 'unspeak': 'retract',
 'overfraught': 'overburdened',
 'fenny': 'marshland dwelling',
 'howlet': 'young owl',
 'ravined': 'glutted',
 'chaudron': 'entrails',
 'enshield': 'shielded',
 'prolixious': 'tedious',
 'overweighs': 'exceeds',
 'unshapes': 'destroys',
 'disvalued': 'discredited',
 'undiscernible': 'indiscernible',
 'perdurably': 'eternally',
 'seemers': 'pretenders',
 'hollowly': 'insincerely',
 'offenseful': 'sinful',
 'benedicite': 'may God be with you',
 'combinate': 'promised',
 'unskillfully': 'foolishly',
 'unhurtful': 'harmless',
 'straitness': 'strictness',
 'unsisting': 'unassisting',
 'forerunning': 'foreshadowing',
 'razure': 'obliteration',
 'notedly': 'particularly',
 'attorneyed': 'acting as advocate',
 'instate': 'bestow',
 'gratulate': 'gratifying',
 'cardinally': 'carnally',
 'picklock': 'lockpick',
 'disvouched': 'disavowed',
 'unreverend': 'irreverent',
 'touse': 'tear',
 'giglets': 'harlots',
 'ungot': 'unborn',
 'misreport': 'slander',
 'votarists': 'monk',
 'adoptedly': 'through adoption',
 'schoolmaids': 'schoolgirls',
 'unwedgeable': 'unsplittable',
 'ignomy': 'dishonour',
 'prompture': 'prompting',
 'leiger': 'envoy',
 'vastidity': 'vastness',
 'enew': 'drive into the water',
 'circummured': 'walled around',
 'planched': 'boarded',
 'caracts': 'badges',
 'concupiscible': 'voluptuous',
 'enskied': 'placed in heaven',
 'seedness': 'action of sowing',
 'avised': 'considered',
 'unshunned': 'unavoidable',
 'extirp': 'eradicate',
 'unweighing': 'thoughtless',
 'tundish': 'funnel',
 'ungenitured': 'sterile',
 'untrussing': 'dropping your breeches',
 'cucullus': 'the hood does not make the monk',
 'fleshmonger': 'pimp',
 'belocked': 'locked up',
 'confixed': 'fastened',
 'carman': 'carrier',
 'undoubtful': 'certain',
 'leavy': 'leafy',
 'mountanto': 'fencer',
 'cinquepace': 'capering dance',
 'ancientry': 'old fashioned formality',
 'reportingly': 'hearsay',
 'comfect': 'sweetmeat',
 'continuer': 'enduring person',
 'recheat': 'horn call for bringing hounds together',
 'toothpicker': 'toothpick',
 'carpetmongers': 'ladies man',
 'fashionmonging': 'dealing in fashions',
 'anticly': 'buffoon',
 'desartless': 'underserving',
 'vagrom': 'vagrant',
 'decerns': 'concern',
 'aspicious': 'auspicious',
 'suffigance': 'sufficient',
 'noncome': 'nonplussed',
 'dissembly': 'assembly',
 'eftest': 'quickest',
 'opinioned': 'pinioned',
 'empoison': 'corrupt',
 'sevennight': 'week',
 'preceptial': 'full of wise instructions',
 'lustihood': 'lustiness',
 'underborne': ' trimmed at the bottom',
 'untowardly': 'unfavourably',
 'eightscore': 'one hundred sixty',
 'circumstanced': 'subject to the situation',
 'guardage': 'protection',
 'bondslaves': 'slave',
 'ingener': 'inventor',
 'ensteeped': 'submerged',
 'sennight': 'week',
 'extincted': 'extinguished',
 'enwheel': 'encircle',
 'twiggen': 'wickerwork',
 'unperfectness': 'imperfection',
 'waterish': 'watered down',
 'continuate': 'enduring',
 'dispraisingly': 'disparagingly',
 'crusadoes': 'gold coin',
 'startingly': 'disjointedly',
 'advocation': 'pleading',
 'observancy': 'proper attention',
 'grise': 'step',
 'slubber': 'careless ',
 'hungerly': 'sparse',
 'bewhored': 'make a whore of',
 'disproportioned': 'inconsistent',
 'importancy': 'importance',
 'reprobance': 'damnation',
 'nonsuits': 'refuse',
 'yerked': 'beat',
 'unbitted': 'unrestrained',
 'coloquintida': 'bitter apple',
 'disrelish': 'distaste',
 'displanting': 'removing',
 'almain': 'German',
 'lown': 'sluggard',
 'denotement': 'indication',
 'probal': 'reasonable',
 'enfettered': 'enslaved',
 'whereinto': 'in which',
 'leets': 'local court of justice',
 'fineless': 'boundless',
 'acknown': 'acknowledge',
 'unproper': 'improperly',
 'scuses': 'excuses',
 'encave': 'conceal',
 'unbookish': 'ignorant',
 'uncapable': 'incapable',
 'gastness': 'terror',
 'restem': 'retrace',
 'ensheltered': 'within shelter',
 'embayed': 'protected by the shore',
 'signiory': 'estate',
 'unhoused': 'unprotected',
 'antres': 'caverns',
 'anthropophagi': 'cannibals',
 'intentively': 'paying continuous attention',
 'indign': 'shameful',
 'outsport': 'revel beyond the limits of',
 'exsufflicate': 'inflated',
 'chamberers': 'frequenter of ladies chambers',
 'prerogatived': 'privileged',
 'sybil': 'prophet',
 'unprovide': 'unequip',
 'procreants': 'copulators',
 'relume': 'rekindle',
 'iterance': 'repetition',
 'whipster': 'degenerate',
 'incontinently': 'immediately',
 'conveniency': 'opportunity',
 'votaress': 'votary',
 'fopped': 'duped',
 'designment': 'undertaking',
 'arrivance': 'arriving',
 'adventerous': 'adventurous',
 'womenkind': 'all women',
 'disfurnish': 'deprive',
 'cavalleria': 'society of knights',
 'pothecary': 'apothecary',
 'vegetives': 'vegetables',
 'bitumed': 'smeared with pitch',
 'entreasured': 'kept as in a treasury',
 'aland': 'on shore',
 'distain': 'eclipse',
 'wanion': 'with a vengeance',
 'welladay': 'lamentation',
 'quotha': 'did he say indeed',
 'moreofer': 'as well as the fact',
 'whipstock': 'whip handle',
 'speken': 'speak',
 'eche': 'increase',
 'dern': 'dark',
 'sleided': 'filamented',
 'prest': 'made ready',
 'dumbs': 'silences',
 'neele': 'needle',
 'effectless': 'ineffective',
 'roguing': 'villainous',
 'resorters': 'regulars',
 'herbwoman': 'woman who sells herbs',
 'thoughten': 'thinking',
 'questionless': 'unquestionably',
 'coistrel': 'knave',
 'wenchless': 'lacking in women',
 'chequins': 'gold coin',
 'misdread': 'fear of harm',
 'finny': 'provided with fins',
 'eftsoons': 'afterwards',
 'appearer': 'one who arrives on the scene',
 'craver': 'supplicant',
 'condolements': 'lamenting',
 'vails': 'lowers',
 'searoom': 'space at sea to manoeuvre a ship',
 'husht': 'be quiet',
 'apprenticehood': 'apprenticeship',
 'unthrifts': 'squanderers',
 'imprese': 'emblem',
 'bedrench': 'soak',
 'unpossible': 'impossible',
 'wishtly': 'intently',
 'seely': 'pathetic',
 'apricokes': 'apricots',
 'supportance': 'reinforcement',
 'bewasted': 'wasted away',
 'unstaid': 'unsteady',
 'undeaf': 'restore hearing to',
 'bondslave': 'slave',
 'unthrifty': 'squandering',
 'partialize': 'bias',
 'underbearing': 'enduring',
 'oysterwench': 'oyster woman',
 'draymen': 'men who drive a cart without wheels',
 'sullens': 'dulls',
 'rugheaded': 'shaggy headed',
 'discomfortable': 'discouraging',
 'monarchize': 'perform the role of a monarch',
 'almsman': 'person living through charitable offerings',
 'unkinged': 'dethroned',
 'undeck': 'unclothe',
 'sprightfully': 'spiritedly',
 'broking': 'acting as a broker',
 'whencesoever': 'from whatever place',
 'jauncing': 'prancing',
 'pilled': 'made bald',
 'burdenous': 'oppressive',
 'whitebeards': 'old men',
 'deceivable': 'deceptive',
 'bespake': 'requested',
 'appeach': 'denounce',
 'overshade': 'overshadow',
 'straitly': 'strictly',
 'unsatiate': 'voracious',
 'recure': 'heal',
 'crossrow': 'alphabet',
 'methoughts': 'seemed to me',
 'overgo': 'exceed',
 'gramercy': 'great thanks',
 'fearfull': 'frighteningly',
 'unblown': 'immature',
 'overpast': 'former',
 'begnaw': 'chew',
 'cockshut': 'evening twilight',
 'overworn': 'spent',
 'abjects': 'despicable',
 'bedashed': 'dashed about',
 'royalize': 'make royal',
 'worshipfully': 'respectfully',
 'disgracious': 'disliked',
 'unrespective': 'undiscriminating',
 'victoress': 'victor',
 'recomforture': 'solace',
 'hoyday': 'impatience',
 'battalia': 'marshalled force',
 'foreward': 'vanguard',
 'overcloyed': 'overfilled',
 'embowelled': 'disembowelled',
 'peise': 'poise',
 'unattainted': 'detached',
 'princox': 'impertinent youth',
 'mammet': 'puppet',
 'fleckled': 'speckled',
 'uproused': 'get up',
 'skilless': 'ignorant',
 'endart': 'embed arrow',
 'bescreened': 'cover up',
 'bepaint': 'cover over',
 'coying': 'deviousness',
 'highmost': 'highest',
 'needly': 'unavoidably',
 'reeky': 'foul smelling',
 'behooveful': 'necessary',
 'ambuscadoes': 'ambushes',
 'elflocks': 'matted locks',
 'poperin': 'pear',
 'punto': 'thrust with the sword',
 'reverso': 'reverse',
 'hildings': 'worthless individuals',
 'pilcher': 'shitty scabbard',
 'holidam': 'holy swear',
 'ropery': 'tricks',
 'skains': 'cut throat fellow',
 'versal': 'universal',
 'weraday': 'alas',
 'markman': 'marksman',
 'overperch': 'surmount',
 'displant': 'remove',
 'betossed': 'tossed about',
 'distemperatures': 'disorders',
 'defeatures': 'disfigurements',
 'strumpeted': 'whored',
 'distained': 'eclipsed',
 'stigmatical': 'disfigured',
 'chargeful': 'lavish',
 'debted': 'indebted',
 'carcanet': 'jewelled necklace',
 'dankish': 'dank',
 'undisposed': 'indisposed',
 'falsing': 'deceptive',
 'respice': 'think of your end',
 'overembellished': '',
 'fraughtage': 'luggage',
 'balsamum': 'balsam',
 'waftage': 'passage',
 'dowsabel': 'sweetheart',
 'backfriend': 'false friend',
 'dryfoot': ' hunting by following the scent of the feet',
 'disannul': 'annul',
 'misconstered': 'misconstrued',
 'guiled': 'deceiving',
 'blent': 'blended',
 'sonties': 'saints',
 'sandblind': 'half blind',
 'gree': 'agree',
 'outdwells': 'stays beyond',
 'overweathered': 'weather worn',
 'inexecrable': 'inexorable',
 'overtrip': 'skip over',
 'fia': 'hurry up',
 'frutify': 'certify',
 'masquing': 'elaborate',
 'unthrift': 'squanderer',
 'patens': 'shining circles',
 'stockish': 'stupid',
 'regreets': 'greet again',
 'sophy': 'Abbas ',
 'solyman': 'Suleiman',
 'overstare': 'outstare',
 'throughfares': 'thoroughfares',

            }

def th_dict():
    return  {
             'hateth': 'hates',
             'doth': 'does',
             'hath': 'has',
             'stayeth':  'stays',
             'constraineth':  'constrains',
             'hateth':  'hates',
             'knitteth':  'knits',
             'witnesseth':  'witnesses',
             'presenteth':  'presents',
             'mistaketh':  'mistakes',
             'charmeth':  'charm',
             'quoth':  'quoted',
             'nourisheth':  'nourishes',
             'presageth':  'presages',
             'pleaseth':  'pleases',
             'importeth':  'imports',
             'purposeth':  'purposes',
             'perceiveth':  'perceives',
             'teacheth':  'teaches',
             'pierceth':  'pierces',
             'provoketh':  'provokes',
             'feedeth':  'feedes',
             'placeth':  'places',
             'sufficeth':  'suffices',
             'appeareth':  'appears',
             'sith':  'since',
             'returneth':  'returns',
             'turneth':  'turns',
             'singeth':  'sings',
             'confesseth':  'confesses',
             'deceiveth':  'deceives',
             'liveth':  'lives',
             'wisheth':  'wishes',
             'doteth':  'dotes',
             'promiseth':  'promises',
             'loseth':  'loses',
             'exceedeth':  'exceeds',
             'useth':  'uses',
             'buildeth':  'builds',
             'illumineth':  'illuminates',
             'bleedeth':  'bleeds',
             'standeth':  'stands',
             'saith':  'says',
             'lurketh':  'lurks',
             'feith':  'wait',
             'sendeth':  'sends',
             'cometh':  'comes',
             'wherewith':  'where with',
             'killeth':  'kills',
             'sueth':  'sues',
             'approacheth':  'approaches',
             'serveth':  'serves',
             'perisheth':  'perishes',
             'wanteth':  'wants',
             'giveth':  'gives',
             'ceaseth':  'ceases',
             'joineth':  'joins',
             'droopeth':  'droops',
             'warranteth':  'warrants',
             'remaineth':  'remains',
             'fighteth':  'fights',
             'flieth':  'flies',
             'toucheth':  'touchs',
             'forsaketh':  'forsakes',
             'bindeth':  'binds',
             'bringeth':  'brings',
             'vieweth':  'views',
             'chaseth':  'chases',
             'yoketh':  'yokes',
             'razeth':  'razes',
             'craveth':  'craves',
             'fitteth':  'fits',
             'holdeth':  'holds',
             'preferreth':  'prefers',
             'willeth':  'wills',
             'asketh':  'asks',
             'contenteth':  'contents',
             'seemeth':  'seems',
             'marcheth':  'marches',
             'proclaimeth':  'proclaims',
             'prevaileth':  'prevails',
             'passeth':  'passes',
             'meseemeth':  'seems',
             'accordeth':  'accords',
             'maketh':  'makes',
             'inferreth':  'infers',
             'misdoubteth':  'disbelieves',
             'speaketh':  'speaks',
             'waiteth':  'waits',
             'suppresseth':  'suppresses',
             'proveth':  'proves',
             'requireth':  'requires',
             'resteth':  'rests',
             'increaseth':  'increases',
             'melteth':  'melts',
             'vexeth':  'vexes',
             'burneth':  'burns',
             'mounteth':  'mounts',
             'raileth':  'rails',
             'snarleth':  'snarls',
             'intendeth':  'intends',
             'upholdeth':  'upholds',
             'possesseth':  'possesses',
             'resolveth':  'resolves',
             'assaileth':  'assails',
             'affecteth':  'affects',
             'clippeth':  'clips',
             'rageth':  'rages',
             'raineth':  'rains',
             'loveth':  'loves',
             'rejoiceth':  'rejoices',
             'hunteth':  'hunts',
             'hangeth':  'hangs',
             'falleth':  'falls',
             'saluteth':  'salutes',
             'understandeth':  'understands',
             'draweth':  'draws',
             'clepeth':  'calls',
             'insinuateth':  'insinuates',
             'beseemeth':  'seems',
             'expresseth':  'expresses',
             'purchaseth':  'purchases',
             'affordeth':  'affords',
             'ariseth':  'arises',
             'enticeth':  'entices',
             'enjoineth':  'enjoins',
             'danceth':  'dances',
             'reacheth':  'reaches',
             'lanceth':  'lances',
             'oppresseth':  'oppresses',
             'lieth':  'lies',
             'boundeth':  'bounds',
             'shineth':  'shines',
             'thrusteth':  'thrusts',
             'reposeth':  'reposes',
             'ensnareth':  'ensnares',
             'rideth':  'rides',
             'adoreth':  'adores',
             'encompasseth':  'encompasses',
             'encloseth':  'encloses',
             'jumpeth':  'jumps',
             'accuseth':  'accuses',
             'rooteth':  'roots',
             'divideth':  'divides',
             'driveth':  'drives',
             'heareth':  'hears',
             'stirreth':  'stirs',
             'moveth':  'moves',
             'starveth':  'starves',
             'chargeth':  'charges',
             'loureth':  'frowns',
             'springeth':  'springs',
             'consisteth':  'consists',
             'chooseth':  'chooses',
             'riseth':  'rises',
             'attendeth':  'attends',
             'droppeth':  'drops',
             'blesseth':  'blesses',
             'enlargeth':  'enlarges',
             'taketh':  'takes',
             'oweth':  'owes',
             'groweth':  'grows',
             'beareth':  'bears',
             'uttereth':  'utters',
             'planteth':  'plants',
             'peereth':  'peers',
             'flourisheth':  'flourishes',
             'concerneth':  'concerns',
             'longeth':  'longs',
             'surpasseth':  'surpasses',
             'betideth':  'betides',
             'overtaketh':  'overtakes',
             'despiseth':  'despises',
             'resembleth':  'resembles',
             'meaneth':  'means',
             'esteemeth':  'esteems',
             'fawneth':  'fawns',
             'spilth':  'spills',
             'climbeth':  'climbs',
             'glideth':  'glids',
             'seizeth':  'seizes',
             'offendeth':  'offends',
             'disdaineth':  'disdains',
             'tosseth':  'tosses',
             'playeth':  'plays',
             'violenteth':  'violent',
             'causeth':  'causes',
             'moldeth':  'molds',
             'receiveth':  'receives',
             'unfoldeth':  'unfolds',
             'forsooth':  'doubt',
             'forthwith':  'immediately',
             'japheth':  'japes',
             'wroth':  'wrath',
             'goliath':  'goliath'
         }

def shakespeare_contractions_dict():
    return {
            "ta'en": "taken",
            "e'en": "even",
            "fall'n": "fallen",
            "threat'ning": "threatening",
            "wand'ring": "wandering",
            "wat'ry": "watery",
            "ev'ry": "every",
            "ev'n": "even",
            "med'cine": "medicine",
            "ling'ring": "lingering",
            "boist'rous": "boisterous",
            "murd'rous": "murderous",
            "desp'rate": "desperate",
            "reck'ning": "reckoning",
            "wond'ring": "wondering",
            "sland'rous": "slanderous",
            "count'nance": "countenance",
            "mock'ry": "mockery",
            "murd'ring": "murdering",
            "batt'ry": "battery",
            "tend'ring": "tendering",
            "list'ning": "listening",
            "tott'ring": "tottering",
            "flow'ring": "flowering",
            "giv'n": "given",
            "fee'd": "payed",
            "numb'ring": "numbering",
            "suff'rance": "sufferance",
            "adult'ress": "adulteress",
            "swoll'n": "swollen",
            "rememb'ring": "remembering",
            "rememb'rest": "remembers",
            "flow'ry": "flowery",
            "diff'ring": "differing",
            "suff'ring": "suffering",
            "slipp'ry": "slippery",
            "med'cinable": "medicinable",
            "slaught'ring": "slaughtering",
            "distemp'rature": "distemperature",
            "off'ring": "offering",
            "glist'ring": "glistering",
            "card'nal": "cardinal",
            "off'rings": "offerings",
            "lott'ry": "lottery",
            "whisp'ring": "whispering",
            "vot'ress": "votress",
            "swagg'ring": "swaggering",
            "prepost'rously": "preposterously",
            "inter'gatories": "interogatories",
            "oferta'en": "overtaken",
            "prosp'rous": "prosperous",
            "conqu'ring": "conquering",
            "utt'rance": "utterance",
            "clamb'ring": "clambering",
            "encount'ring": "encountering",
            "overta'en": "overtaken",
            "temp'rately": "temperately",
            "h'as": "he has",
            "tow'ring": "towering",
            "cap'ring": "capering",
            "glitt'ring": "glittering",
            "blust'ring": "blustering",
            "show'ring": "showering",
            "temp'ring": "tempering",
            "crook'd": "crooked",
            "flatt'ring": "flattering",
            "rend'ring": "rendering",
            "clust'ring": "clustering",
            "heav'ns": "heavens",
            "call'dst": "called",
            "chatt'ring": "chattering",
            "ent'ring": "entering",
            "dark'ning": "darkening",
            "heav'nly": "heavenly",
            "temp'rance": "temperance",
            "heav'n": "heaven",
            "dang'rous": "dangerous",
            "eas'ly": "easily",
            "simp'ring": "simpering",
            "prepost'rous": "preposterous",
            "quick'ning": "quickening",
            "advent'rous": "adventerous",
            "mista'en": "mistaken",
            "blubb'ring": "blubbering",
            "bitt'rest": "bitterest",
            "int'rest": "interest",
            "beck'ning": "beckoning",
            "ord'ring": "ordering",
            "show'rs": "showers",
            "hind'ring": "hindering",
            "phys'nomy": "physiognomy",
            "butt'ring": "buttering",
            "threat'ningly": "threateningly",
            "discov'ryseek": "discoveryseek",
            "liv'ry": "livery",
            "recov'ry": "recovery",
            "squand'ring": "squandering",
            "se'nnight": "week",
            "palt'ring": "paltering",
            "hard'ning": "hardening",
            "dark'ned": "darkened",
            "pest'ring": "pestering",
            "marv'llous": "marvellous",
            "ord'nance": "ordinance",
            "eas'liest": "most easily",
            "length'ning": "lengthening",
            "sulf'rous": "sulfurous",
            "gard'ners": "gardeners",
            "plast'ring": "plastering",
            "rend'ring": "rendering",
            "minist'ring": "ministering",
            "flow'rets": "flowerets",
            "j'oublie": "j'oublie",
            "slobb'ry": "slobbery",
            "mock'ries": "mockeries",
            "furth'rance": "furtherance",
            "powd'ring": "powdering",
            "bach'lorship": "bachelorship",
            "suck'dst": "sucked",
            "short'ning": "shortening",
            "lov'dst": "loved",
            "cow'red": "cowered",
            "trait'rous": "traiterous",
            "strength'ning": "strengthening",
            "sov'reigns": "sovereigns",
            "pow'rful": "powerful",
            "rav'nous": "ravenous",
            "boist'rous": "boisterous",
            "threat'ner": "threatener",
            "ang'ring": "angering",
            "unfee'd": "unpayed",
            "wat'rish": "watery",
            "pilf'rings": "pilferings",
            "flick'ring": "flickering",
            "sepulch'ring": "entombing",
            "sulph'rous": "sulphurous",
            "op'ning": "opening",
            "fost'ring": "fostering",
            "slumb'ry": "slumbery",
            "whisp'rings": "whisperings",
            "sev'nnights": "weeks",
            "vap'rous": "vaporous",
            "temp'rate": "temperate",
            "oft'ner": "more often",
            "med'cines": "medicines",
            "reck'nings": "reckonings",
            "distemp'ring": "distempering",
            "mamm'ring": "wavering",
            "wond'ringly": "wonderingly",
            "deaf'ning": "deafening",
            "thund'ring": "thundering",
            "gard'ner": "gardener",
            "ha'rfordwest": "Haverfordwest",
            "monast'ry": "monastery",
            "marv'lous": "marvelous",
            "check'ring": "checkering",
            "fest'ring": "festering",
            "pop'rin": "poperin",
            "light'ning": "lightening",
            "desp'rately": "desperately",
            "moi'ty": "part",
            "christ'ning": "christening",
            "inter'gatory": "interogatory",
            "cap'ring": "capering",
            "shudd'ring": "shuddering",
            "fopp'ry": "foppishness",
            "jack'nape": "jackanape",
            "dean'ry": "deanery",
            "wat'ry": "watery",
            "sev'ral": "several",
            "em'rald": "emerald",
            "heark'ning": "listening",
            "brav'ry": "bravery",
            "knav'ry": "knavery",
            "off'rest": "offers",
            "fing'ring": "fingering",
            "vow'dst": "vowed",
            "suff'rers": "sufferers",
            "diff'rence": "difference",
            "intemp'rate": "intemperate",
            "blist'ring": "blistering",
            "mast'ry": "mastery",
            "penn'orth": "pennyworth",
            "deaf'ning": "deafening",
            "sev'nnight": "week",
            "hard'ning": "hardening",
            "underta'en": "undertaken",
            "hast'ningin": "hasteningin",
            "alt'ring": "altering",
            "far'r": "farer",
            "glutt'nous": "gluttinous",
            "sold'rest": "solders",
            "gen'ral": "general",
            "thund'rest": "thunders",
            "sust'nance": "sustenance",
            "flatt'ry": "flattery",
            "sequest'ring": "sequestering",
            "regist'red": "registered",
            "t'other": "the other",
            "thiev'ry": "thievery",
            "mapp'ry": "mappery",
            "reverb'rate": "reverberate",
            "int'rim": "interim",
            "chev'ril": "cheveril",
            "butt'ry": "buttery",
            "know'st": "knows",
            "think'st": "thinks",
            "dar'st": "dares",
            "speak'st": "speaks",
            "cam'st": "came",
            "com'st": "comes",
            "mak'st": "makes",
            "be'st": "is",
            "lov'st": "loves",
            "say'st": "says",
            "stand'st": "stands",
            "tell'st": "tells",
            "gav'st": "gave",
            "call'st": "calls",
            "tak'st": "takes",
            "mean'st": "means",
            "liv'st": "lives",
            "look'st": "looks",
            "knew'st": "knew",
            "keep'st": "keeps",
            "talk'st": "talks",
            "dear'st": "dearest",
            "kill'st": "kills",
            "saw'st": "saw",
            "weep'st": "weeps",
            "hear'st": "hears",
            "mad'st": "made",
            "seek'st": "seeks",
            "bear'st": "bears",
            "wrong'st": "wrong",
            "swear'st": "swear",
            "wak'st": "wakes",
            "did'st": "did",
            "bring'st": "brought",
            "seem'st": "seems",
            "need'st": "needs",
            "giv'st": "gives",
            "told'st": "told",
            "hold'st": "holds",
            "runn'st": "runs",
            "bidd'st": "bids",
            "find'st": "finds",
            "dream'st": "dreams",
            "fall'st": "falls",
            "wear'st": "wears",
            "sleep'st": "sleeps",
            "ow'st": "owes",
            "desir'st": "desires",
            "lik'st": "likes",
            "bleed'st": "bleeds",
            "behold'st": "beholds",
            "swor'st": "swore",
            "mov'st": "moves",
            "loud'st": "loudest",
            "long'st": "longest",
            "usurp'st": "usurps",
            "said'st": "said",
            "serv'st": "serves",
            "sham'st": "shamed",
            "fear'st": "fears",
            "lack'st": "lacks",
            "entertain'st": "entertains",
            "prim'st": "primmest",
            "fin'st": "finest",
            "spok'st": "spoke",
            "mistak'st": "mistakes",
            "took'st": "took",
            "hop'st": "hopes",
            "dislik'st": "dislikes",
            "poor'st": "poorest",
            "strik'st": "strikes",
            "looked'st": "looked",
            "foul'st": "foulest",
            "far'st": "fare",
            "had'st": "had",
            "offer'st": "offer",
            "warr'st": "war",
            "lead'st": "lead",
            "dwell'st": "dwells",
            "suck'st": "sucks",
            "barr'st": "barest",
            "would'st": "would",
            "grew'st": "grew",
            "becom'st": "becomes",
            "turn'st": "turns",
            "ran'st": "ran",
            "provok'st": "provokes",
            "hid'st": "hides",
            "shak'st": "shakes",
            "suffer'st": "suffers",
            "drink'st": "drinks",
            "command'st": "commands",
            "join'st": "joins",
            "spak'st": "spoke",
            "deserv'st": "deserves",
            "woefull'st": "most woefull",
            "lay'st": "lays",
            "break'st": "breaks",
            "smil'st": "smiles",
            "may'st": "may",
            "esteem'st": "esteems",
            "near'st": "nearest",
            "sing'st": "sings",
            "stirr'st": "stirs",
            "chid'st": "chides",
            "strong'st": "strongest",
            "holp'st": "hopes",
            "cop'st": "copes",
            "bad'st": "bade",
            "answer'st": "answers",
            "feed'st": "feeds",
            "heard'st": "heard",
            "feel'st": "feels",
            "wor'st": "wore",
            "fair'st": "fairest",
            "draw'st": "draws",
            "mock'st": "mocks",
            "driv'st": "drives",
            "robb'st": "robs",
            "high'st": "highest",
            "heedfull'st": "heedfull",
            "disdain'st": "disdains",
            "quick'st": "quickest",
            "methink'st": "methinks",
            "fell'st": "fell",
            "slew'st": "slew",
            "remember'st": "remember",
            "prun'st": "prunes",
            "frail'st": "frailest",
            "you'st": "you",
            "can'st": "can",
            "young'st": "youngest",
            "restrain'st": "restrains",
            "blazon'st": "blazoned",
            "rud'st": "rudest",
            "died'st": "died",
            "heap'st": "heaps",
            "ey'st": "eyes",
            "rar'st": "rarest",
            "tender'st": "tenderest",
            "disprov'st": "disproves",
            "loyal'st": "loyalest",
            "ask'st": "asks",
            "endur'st": "endures",
            "pray'st": "prays",
            "walk'st": "walks",
            "drunk'st": "drank",
            "howl'st": "howls",
            "threw'st": "threw",
            "hang'st": "hangs",
            "foul-mouthed'st": "most foul-mouthed",
            "followed'st": "followed",
            "loved'st": "loved",
            "ragged'st": "most ragged",
            "scald'st": "scalds",
            "play'st": "plays",
            "promised'st": "promised",
            "trail'st": "trails",
            "contrived'st": "contrived",
            "laid'st": "laid",
            "spy'st": "spies",
            "magnifi'st": "magnifies",
            "laugh'st": "laughs",
            "intend'st": "intends",
            "behaved'st": "behaved",
            "struck'st": "struck",
            "smooth'st": "smoothest",
            "whil'st": "while",
            "lying'st": "lying",
            "rann'st": "ran",
            "civil'st": "most civil",
            "denied'st": "denied",
            "pitied'st": "pitied",
            "obeyed'st": "obeyed",
            "preferr'st": "preferred",
            "sprawl'st": "sprawls",
            "sprang'st": "sprang",
            "could'st": "could",
            "dipped'st": "dipped",
            "daring'st": "most daring",
            "sharp'st": "sharpest",
            "willing'st": "most willing",
            "aim'st": "aims",
            "sooth'st": "soothes",
            "scorn'st": "scorns",
            "bor'st": "bores",
            "cold'st": "coldest",
            "contemned'st": "condemned",
            "deny'st": "denies",
            "whipp'st": "whips",
            "shin'st": "shines",
            "exhal'st": "exhales",
            "kind'st": "kindest",
            "played'st": "played",
            "stern'st": "sternest",
            "marshal'st": "marshal",
            "marvel'st": "marvels",
            "labor'st": "labors",
            "striv'st": "strives",
            "wholesom'st": "most wholesome",
            "squar'st": "squares",
            "damned'st": "damnedest",
            "wicked'st": "wickedest",
            "conclud'st": "concludes",
            "prick'st": "pricks",
            "began'st": "began",
            "proper'st": "proper",
            "small'st": "smallest",
            "discern'st": "discerns",
            "cried'st": "cried",
            "weigh'st": "weighs",
            "smell'st": "smells",
            "cunning'st": "most cunning",
            "deal'st": "deals",
            "daff'st": "push away",
            "pained'st": "pained",
            "reproved'st": "reproved",
            "showed'st": "showed",
            "read'st": "reads",
            "tread'st": "treads",
            "swell'st": "swells",
            "common'st": "most common",
            "wedd'st": "weds",
            "wretched'st": "most wretched",
            "help'st": "helps",
            "stabbed'st": "stabbed",
            "fearfull'st": "most fearfull",
            "killed'st": "killed",
            "strew'st": "strewn",
            "drew'st": "drew",
            "stay'st": "stays",
            "abound'st": "abounds",
            "found'st": "found",
            "overheard'st": "overheard",
            "threaten'st": "threatens",
            "cheer'st": "cheers",
            "cursed'st": "cursed",
            "spend'st": "spends",
            "stick'st": "sticks",
            "offend'st": "offends",
            "see'st": "sees",
            "eld'st": "eldest",
            "wink'st": "winks",
            "called'st": "called",
            "strok'st": "strokes",
            "wid'st": "widest",
            "attend'st": "attends",
            "murmur'st": "murmurs",
            "shrugg'st": "shrugs",
            "follow'st": "follows",
            "damm'st": "damndest",
            "black'st": "blackest",
            "deem'st": "deems",
            "heal'st": "heals",
            "cur'st": "cures",
            "kenn'st": "know",
            "allow'st": "allows",
            "void'st": "voids",
            "add'st": "adds",
            "reign'st": "reigns",
            "certain'st": "certain",
            "earn'st": "earns",
            "new'st": "newest",
            "fellow'st": "fellows",
            "inclin'st": "inclines",
            "bold'st": "boldest",
            "bid'st": "bids",
            "ail'st": "ails",
            "abhorred'st": "abhorred",
            "scorned'st": "scorned",
            "apprehend'st": "apprehends",
            "outrunn'st": "outrun",
            "flatter'st": "flatters",
            "lived'st": "lived",
            "disclaim'st": "disclaims",
            "redeem'st": "redeems",
            "rigg'st": "rigs",
            "plow'st": "plows",
            "reverend'st": "reverend",
            "dismal'st": "most dismal",
            "proud'st": "proudest",
            "begg'st": "begs",
            "dismall'st": "most dismal",
            "borrowd'st": "borrowed",
            "understand'st": "understands",
            "sigh'st": "sighs",
            "bark'st": "barks",
            "mourn'st": "mourns",
            "faithful'st": "most faithful",
            "cruel'st": "cruelest",
            "car'st": "cares",
            "discov'ry": "discovery",
            "falc'ner": "falconer",
            "cur'sies": "curtsies",
            "cock'rel": "cockerel",
            "cur'sy": "curtsy"
        }

def st_dict():
    return  {
             'dost': 'does',
             'didst': 'did',
             'hast': 'has',
             'durst': 'dares',
             'lovest': 'loves',
             'mayst': 'may',
             'canst': 'can',
             'couldst': 'could',
             'seest': 'see',
             'committost': 'commits',
             'wast': 'was',
             'sayest': 'say',
             'speakest': 'speak',
             'whilst': 'while',
             'desirest': 'desire',
             'engrossest': 'engrosses',
             'greatost': 'greatest',
             'gainst': 'against',
             'shouldst': 'should',
             'thoughtost': 'thought',
             'sayst': 'sats',
             'hadst': 'had',
             'diest': 'dies',
             'keptost': 'kept',
             'wouldst': 'would',
             'fumblest': 'fumbles',
             'departost': 'departs',
             'defeatost': 'defeats',
             'teachest': 'teaches',
             'foughtost': 'fought',
             'blushest': 'blush',
             'vanishest': 'vanishes',
             'pleasest': 'pleases',
             'beest': 'be',
             'mightst': 'might',
             'losest': 'loes',
             'perishest': 'perishes',
             'whilest': 'while',
             'mongst': 'amongst',
             'fittost': 'fittest',
             'sweetost': 'sweetest',
             'questionedst': 'questioned',
             'tirest': 'tire',
             'pursuest': 'pursue',
             'veriest': 'varies',
             'changest': 'changes',
             'answerest': 'answers',
             'knowest': 'knows',
             'worshipest': 'most worshiped',
             'bearest': 'bears',
             'rascaliest': 'most rascally',
             'darest': 'dares',
             'comest': 'comes',
             'spendest': 'spends',
             'keepest': 'keeps',
             'owest': 'owes',
             'variest': 'most varied',
             'talkest': 'talks',
             'givest': 'gives',
             'standest': 'stands',
             'bleedest': 'bleeds',
             'pourest': 'pours',
             'judgest': 'judges',
             'gavest': 'gave',
             'stolest': 'stole',
             'sawest': 'saw',
             'swearest': 'swear',
             'criest': 'cry',
             'leavest': 'leaves',
             'tremblest': 'trembles',
             'reportost': 'reports',
             'thinkest': 'thinks',
             'usest': 'uses',
             'doubtost': 'doubt',
             'vanquishest': 'vanquish',
             'fightest': 'fight',
             'askst': 'ask',
             'laughest': 'laugh',
             'lookest': 'look',
             'oughtst': 'ought',
             'threatest': 'threaten',
             'trowest': 'throw',
             'aimest': 'aim',
             'smiledst': 'smiled',
             'wishest': 'wishes',
             'mayest': 'may',
             'receivest': 'receive',
             'criedst': 'cried',
             'lovedst': 'loved',
             'urgest': 'urges',
             'indigest': 'indigestion',
             'sleepest': 'sleep',
             'wakest': 'wakes',
             'maidenliest': 'most maidenly',
             'showest': 'shows',
             'throwest': 'throws',
             'remembrest': 'remembers',
             'makest': 'makes',
             'grievest': 'grieves',
             'crushest': 'crushes',
             'wouldest': 'would',
             'ratherest': 'rather',
             'viewest': 'view',
             'beholdest': 'behold',
             'surveyest': 'survey',
             'ridest': 'rides',
             'speakst': 'speak',
             'interruptest': 'interrupt',
             'perfectost': 'most perfect',
             'secretost': 'most secret',
             'anticipatost': 'most anticipated',
             'repeatost': 'repeated',
             'forgetost': 'forgotten',
             'causest': 'causes',
             'believest': 'believes',
             'deservest': 'deserves',
             'overheardst': 'overheard',
             'beliest': 'belies',
             'pleasantost': 'most pleasant',
             'praisest': 'praise',
             'owedst': 'owed',
             'echofst': 'echoes',
             'saidst': 'said',
             'unblest': 'unblessed',
             'toldst': 'told',
             'suppliest': 'supplied',
             'professest': 'profess',
             'rudeliest': 'most rude',
             'seemest': 'seems',
             'begetost': 'begets',
             'woefullest': 'most woefull',
             'deniest': 'denies',
             'returnest': 'return',
             'respectost': 'respect',
             'breathest': 'breathe',
             'flatterest': 'flatter',
             'takest': 'take',
             'shortost': 'shortest',
             'hopest': 'hopes',
             'lookst': 'look',
             'troublest': 'troubles',
             'supposest': 'suppose',
             'sawst': 'saw',
             'slewest': 'slew',
             'stumblest': 'stumble',
             'camest': 'came',
             'repliest': 'replies',
             'hearest': 'hears',
             'stickest': 'sticks',
             'smilest': 'smiles',
             'spakest': 'spoke',
             'fearest': 'fears',
             'bittorest': 'bitterest',
             'consortest': 'consorts',
             'departedst': 'departed',
             'sorrowest': 'sorrows',
             'intorest': 'interest',
             'unpleasantost': 'most unpleasant',
             'leadest': 'leads',
             'namest': 'name',
             'torturest': 'tortures',
             'accountost': 'accounts',
             'travelest': 'travels',
             'neglectost': 'neglects',
             'payest': 'pays',
             'reportest': 'reports',
             'followest': 'follows',
             'lamentost': 'laments',
             'stayest': 'stays',
             'dischargest': 'discharges',
             'bringst': 'brings',
             'huntost': 'hunts',
             'betrayedst': 'betrayed',
             'ancientost': 'most ancient',
             'knewest': 'knew',
             'settlest': 'settles',
             'adorest': 'adores',
             'gallantost': 'most gallant',
             'dismallest': 'most dismal',
             'findst': 'finds',
             'underhonest': 'dishonest',
             'blowest': 'blows',
             'strikest': 'strikes',
             'grumblest': 'grumbles',
             'vexest': 'vexes',
             'complainest': 'complains',
             'thinkst': 'thinks',
             'honestest': 'most honest',
             'noblest': 'most noble',
             'bluest': 'most blue',
             'goest': 'goes',
             'justest': 'most just',
             'extremest': 'most extreme',
             'stubbornest': 'most stubborn',
             'liest': 'lie',
             'chiefest': 'chief',
             'fellest': 'fell',
             'mutest': 'most mute',
             'loyalest': 'most loyal',
             'inmost': 'innermost',
             'livest': 'lives',
             'profoundest': 'most profound',
             'littlest': 'smallest',
             'accurst': 'accursed',
             'layest': 'lays',
             'sovereignest': 'most sovereign',
             'soldest': 'sold',
             'welcomest': 'welcome',
             'divinest': 'divine',
             'prizest': 'prizes',
             'meetest': 'meet',
             'primest': 'most prim',
             'goodliest': 'most good natured',
             'unkindest': 'most unkind',
             'dunnest': 'most dun',
             'perfectest': 'most perfect',
             'likest': 'like',
             'curstest': 'most cursed',
             'diffusest': 'most diffuse',
             'primmest': 'most prim',
             'exactest': 'most exact',
             'loathsomest': 'most loathsome',
             'escapest': 'escapes'
          }
